### ISSUE TITLE
how

### ISSUE THREAD

**Issue by luke-e-gibson** [perryMELENOHRST/Quest2Colour#1]
it has no color camera. you would need a color webcam pluged into a webcam then stream it to the quest throw wifi or link cable or a vr desktop app

**Comment by perryMELENOHRST** [comment]
attach stereoscopic camera to the front of the quest then feed camera output through usbc port then display it through a sideloaded quest app, its actually not to hard

**Comment by luke-e-gibson** [comment]
Witch one  there from $100 to $1000 or two mono webcams
